### ISSUE TITLE
Create Site

### ISSUE THREAD

**Issue by KeyJ148** [KeyJ148/tow#156]
Сайт, на котором присутствуют четыре кнопочки: "Скачать под Windows", "Скачать под Linux", "Скачать под MacOS" и "Выбор версии".
Последняя переносит на вторую страницу, на которой содержаться три выпадающих списка (ОС, ветки (master, develop, other) и версии) и две кнопочки: "Скачать" и "Назад".

Может быть оставить кнопку "выбор версий" только для нас.

**Comment by Bronuh** [comment]
Начните со странички на [itch.io](https://itch.io/) - пока хватит. Там же оставьте ссылку на сорцы игры. На гитхабе можно хранить старые релизы.

**Comment by KeyJ148** [comment]
Готово: https://tow.abro.cc
