### ISSUE TITLE
Вынести загрузку из TextureStrorage в конфиг

### ISSUE THREAD

**Issue by VasterLordEP** [KeyJ148/tow#16]

**Comment by KeyJ148** [comment]
Было реализовано в cc.abro.orchengine.resources.sprites.SpriteStorage
При рефакторинге надо дать возможность клиенту указывать движку из какого конфига грузить спрайты
Например, ради динамической подгрузки спрайтов при загрузке уровня/локации
https://github.com/KeyJ148/OrchEngine/blob/204c94beb80827ce2ba6e89fb31d64450395caa6/src/main/java/cc/abro/orchengine/resources/sprites/SpriteStorage.java#L14
