### ISSUE TITLE
Create event-bus in OrchEngine

### ISSUE THREAD

**Issue by KeyJ148** [KeyJ148/tow#175]

**Comment by Bronuh** [comment]
![image](https://github.com/KeyJ148/TOW/assets/7189834/12c1c82b-84fe-4282-96df-4e8d601f5cc5)

**Comment by KeyJ148** [comment]
Да норм. Я решил просто Guava заюзать, она вполне похожа на то, что ты спроектировал.
Там только гемор с тем, чтобы делать автоматическую подписку-отписку для объектов, компонентов и сервисов.
![image](https://github.com/KeyJ148/TOW/assets/11208879/922c0672-3ec2-49b5-9f2b-f401c28527cb)
