### ISSUE TITLE
При подборе большей по размере брони можно оказаться в доме/танке

### ISSUE THREAD

**Issue by VasterLordEP** [KeyJ148/tow#6]

**Comment by KeyJ148** [comment]
Временно:
Увеличить дистанцию генерации от домов
Если танки застряли друг в друге (несколько степов подряд срабатывает коллизия, то взрывать)

**Comment by KeyJ148** [comment]
Добавить возможность самоубийства
Решили отказаться от идеи взрывать танки при колизии, т.к. будет негативный пользовательский опыт

**Comment by KeyJ148** [comment]
Добавлена возможность самоубийства в мультиплеере.
Систему выталкивания из объектов будум делать при переделке системы коллизий.
