### ISSUE TITLE
Проблемы с отрисовкой. 

### ISSUE THREAD

**Issue by VasterLordEP** [KeyJ148/tow#7]
Стримлайнд не заметен при повороте патрона на некратный 90 градусам угол,
На пустынной карте деревья при повороте становятся белыми.

В Sprite, перед рендером
if (KeyboardHandler.isKeyDown(Keyboard.KEY_O)){
GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
}
if (KeyboardHandler.isKeyDown(Keyboard.KEY_P)){
GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_LINEAR);
GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_LINEAR);
}

**Comment by KeyJ148** [comment]
Стримлайнд перерисовали
Пробовали два типа филтрации, но GL_NEAREST сильно хуже для любых объектов кроме проблемных деревьев
Проблема с деревьями была из-за прозрачного белого, а не черного фона, исправили

**Comment by KeyJ148** [comment]
Осталось написать скрипт для проверки всех текстур на наличие прозрачных белых пикселей и замену их на черные

**Comment by KeyJ148** [comment]
Все прозрачные пиксели (200к в 66 текстурах) заменены на черные
