### ISSUE TITLE
Сделать класс для переключения между комнатами

### ISSUE THREAD

**Issue by VasterLordEP** [KeyJ148/tow#93]
Сделать сохранение состояний меню при смене комнат
Ленивая инициализация комнат
Вынести вызов в отдельный менеджер с activate, который бы делал freeze и unfreeze, он жн меняет Global.location
https://github.com/KeyJ148/OrchEngine/blob/00577453660eb06eac98a495d8332e3f256e0294/src/main/java/cc/abro/orchengine/map/Location.java#L88
https://github.com/KeyJ148/OrchEngine/blob/00577453660eb06eac98a495d8332e3f256e0294/src/main/java/cc/abro/orchengine/map/Location.java#L104

**Comment by KeyJ148** [comment]
Было исправлено ранее.
